// Generated by tools/generate-blocks.js. Edit the catalog in that file.

//% color=#E9A23B weight=84 block="Light and sound"
//% groups='["Analog"]'
namespace scienceLight {
    /** a-006: connect a 3.3V module to G/V/S of the selected pin. Raw 0..1023; not a calibrated physical unit. P3/P4/P10 turn off the LED display. */
    //% blockId=scienceLight_light block="light sensor $pin raw value" group="Analog" pin.defl=ScienceAnalogPin.P1
    export function light(pin: ScienceAnalogPin): number { return scienceInternal.analog(pin) }
    /** a-007: connect a 3.3V module to G/V/S of the selected pin. Raw 0..1023; not a calibrated physical unit. P3/P4/P10 turn off the LED display. */
    //% blockId=scienceLight_uvRaw block="UV sensor $pin raw value" group="Analog" pin.defl=ScienceAnalogPin.P1
    export function uvRaw(pin: ScienceAnalogPin): number { return scienceInternal.analog(pin) }
    /** a-030: connect a 3.3V module to G/V/S of the selected pin. Raw 0..1023; not a calibrated physical unit. P3/P4/P10 turn off the LED display. */
    //% blockId=scienceLight_sound block="sound sensor $pin raw value" group="Analog" pin.defl=ScienceAnalogPin.P1
    export function sound(pin: ScienceAnalogPin): number { return scienceInternal.analog(pin) }
}

//% color=#248F8F weight=83 block="Water and environment"
//% groups='["Analog","Water temperature(DS18B20)","pH","TDS","Turbidity(AZDM01)"]'
namespace scienceWater {
    /** a-008: connect a 3.3V module to G/V/S of the selected pin. Raw 0..1023; not a calibrated physical unit. P3/P4/P10 turn off the LED display. */
    //% blockId=scienceWater_soilMoisture block="soil moisture sensor $pin raw value" group="Analog" pin.defl=ScienceAnalogPin.P1
    export function soilMoisture(pin: ScienceAnalogPin): number { return scienceInternal.analog(pin) }
    /** a-015: connect a 3.3V module to G/V/S of the selected pin. Raw 0..1023; not a calibrated physical unit. P3/P4/P10 turn off the LED display. */
    //% blockId=scienceWater_water block="water sensor $pin raw value" group="Analog" pin.defl=ScienceAnalogPin.P1
    export function water(pin: ScienceAnalogPin): number { return scienceInternal.analog(pin) }
    /** 2025 orders Sheet1 E26: connect a 3.3V module to G/V/S of the selected pin. Raw 0..1023; not a calibrated physical unit. P3/P4/P10 turn off the LED display. */
    //% blockId=scienceWater_rain block="rain sensor $pin raw value" group="Analog" pin.defl=ScienceAnalogPin.P1
    export function rain(pin: ScienceAnalogPin): number { return scienceInternal.analog(pin) }
}

//% color=#9B59B6 weight=82 block="Force and motion"
//% groups='["Analog","Motion(MPU6050)","Weight","Rotary encoder(EC11)","GPS"]'
namespace scienceMotion {
    /** a-019: connect a 3.3V module to G/V/S of the selected pin. Raw 0..1023; not a calibrated physical unit. P3/P4/P10 turn off the LED display. */
    //% blockId=scienceMotion_vibration block="vibration sensor $pin raw value" group="Analog" pin.defl=ScienceAnalogPin.P1
    export function vibration(pin: ScienceAnalogPin): number { return scienceInternal.analog(pin) }
    /** a-021: connect a 3.3V module to G/V/S of the selected pin. Raw 0..1023; not a calibrated physical unit. P3/P4/P10 turn off the LED display. */
    //% blockId=scienceMotion_magnet block="magnet sensor $pin raw value" group="Analog" pin.defl=ScienceAnalogPin.P1
    export function magnet(pin: ScienceAnalogPin): number { return scienceInternal.analog(pin) }
    /** a-023: connect a 3.3V module to G/V/S of the selected pin. Raw 0..1023; not a calibrated physical unit. P3/P4/P10 turn off the LED display. */
    //% blockId=scienceMotion_force block="force sensor $pin raw value" group="Analog" pin.defl=ScienceAnalogPin.P1
    export function force(pin: ScienceAnalogPin): number { return scienceInternal.analog(pin) }
    /** a-025: connect a 3.3V module to G/V/S of the selected pin. Raw 0..1023; not a calibrated physical unit. P3/P4/P10 turn off the LED display. */
    //% blockId=scienceMotion_rotation block="rotation sensor $pin raw value" group="Analog" pin.defl=ScienceAnalogPin.P1
    export function rotation(pin: ScienceAnalogPin): number { return scienceInternal.analog(pin) }
    /** a-026: connect a 3.3V module to G/V/S of the selected pin. Raw 0..1023; not a calibrated physical unit. P3/P4/P10 turn off the LED display. */
    //% blockId=scienceMotion_infiniteRotation block="continuous rotation sensor $pin raw value" group="Analog" pin.defl=ScienceAnalogPin.P1
    export function infiniteRotation(pin: ScienceAnalogPin): number { return scienceInternal.analog(pin) }
    /** a-027: connect a 3.3V module to G/V/S of the selected pin. Raw 0..1023; not a calibrated physical unit. P3/P4/P10 turn off the LED display. */
    //% blockId=scienceMotion_slider block="slider sensor $pin raw value" group="Analog" pin.defl=ScienceAnalogPin.P1
    export function slider(pin: ScienceAnalogPin): number { return scienceInternal.analog(pin) }
}

//% color=#5C8F3C weight=81 block="Detection and switches"
//% groups='["Analog","Digital","Ultrasonic distance","Color(TCS34725)","Laser distance(VL53L0X)","Gesture sensor(APDS9960)"]'
namespace scienceDetection {
    /** a-022: connect a 3.3V module to G/V/S of the selected pin. Raw 0..1023; not a calibrated physical unit. P3/P4/P10 turn off the LED display. */
    //% blockId=scienceDetection_analogTouch block="4-pad analog touch sensor $pin raw value" group="Analog" pin.defl=ScienceAnalogPin.P1
    export function analogTouch(pin: ScienceAnalogPin): number { return scienceInternal.analog(pin) }
    /** a-029: connect a 3.3V module to G/V/S of the selected pin. Raw 0..1023; not a calibrated physical unit. P3/P4/P10 turn off the LED display. */
    //% blockId=scienceDetection_line block="line sensor $pin raw value" group="Analog" pin.defl=ScienceAnalogPin.P1
    export function line(pin: ScienceAnalogPin): number { return scienceInternal.analog(pin) }
    /** a-031: connect a 3.3V module to G/V/S of the selected pin. Raw 0..1023; not a calibrated physical unit. P3/P4/P10 turn off the LED display. */
    //% blockId=scienceDetection_object block="IR object sensor $pin raw value" group="Analog" pin.defl=ScienceAnalogPin.P1
    export function object(pin: ScienceAnalogPin): number { return scienceInternal.analog(pin) }
    /** d-017~020: connect G/V/S to the selected digital pin. Returns the electrical signal 0 or 1. Module polarity varies. */
    //% blockId=scienceDetection_button block="button $pin signal" group="Digital" pin.defl=ScienceDigitalPin.P8
    export function button(pin: ScienceDigitalPin): number { return scienceInternal.digital(pin) }
    /** d-021: connect G/V/S to the selected digital pin. Returns the electrical signal 0 or 1. Module polarity varies. */
    //% blockId=scienceDetection_switchValue block="rocker switch $pin signal" group="Digital" pin.defl=ScienceDigitalPin.P8
    export function switchValue(pin: ScienceDigitalPin): number { return scienceInternal.digital(pin) }
    /** d-022~026: connect G/V/S to the selected digital pin. Returns the electrical signal 0 or 1. Module polarity varies. */
    //% blockId=scienceDetection_touch block="touch sensor $pin signal" group="Digital" pin.defl=ScienceDigitalPin.P8
    export function touch(pin: ScienceDigitalPin): number { return scienceInternal.digital(pin) }
    /** d-013: connect G/V/S to the selected digital pin. Returns the electrical signal 0 or 1. Module polarity varies. */
    //% blockId=scienceDetection_human block="human presence sensor $pin signal" group="Digital" pin.defl=ScienceDigitalPin.P8
    export function human(pin: ScienceDigitalPin): number { return scienceInternal.digital(pin) }
    /** d-015: connect G/V/S to the selected digital pin. Returns the electrical signal 0 or 1. Module polarity varies. */
    //% blockId=scienceDetection_tilt block="tilt sensor $pin signal" group="Digital" pin.defl=ScienceDigitalPin.P8
    export function tilt(pin: ScienceDigitalPin): number { return scienceInternal.digital(pin) }
    /** d-016: connect G/V/S to the selected digital pin. Returns the electrical signal 0 or 1. Module polarity varies. */
    //% blockId=scienceDetection_vibration block="digital vibration sensor $pin signal" group="Digital" pin.defl=ScienceDigitalPin.P8
    export function vibration(pin: ScienceDigitalPin): number { return scienceInternal.digital(pin) }
    /** d-010: connect G/V/S to the selected digital pin. Returns the electrical signal 0 or 1. Module polarity varies. */
    //% blockId=scienceDetection_waterLevel block="water level sensor $pin signal" group="Digital" pin.defl=ScienceDigitalPin.P8
    export function waterLevel(pin: ScienceDigitalPin): number { return scienceInternal.digital(pin) }
    /** d-012: connect G/V/S to the selected digital pin. Returns the electrical signal 0 or 1. Module polarity varies. */
    //% blockId=scienceDetection_photoGate block="photointerrupter $pin signal" group="Digital" pin.defl=ScienceDigitalPin.P8
    export function photoGate(pin: ScienceDigitalPin): number { return scienceInternal.digital(pin) }
    /** d-027: connect G/V/S to the selected digital pin. Returns the electrical signal 0 or 1. Module polarity varies. */
    //% blockId=scienceDetection_flame block="flame sensor $pin signal" group="Digital" pin.defl=ScienceDigitalPin.P8
    export function flame(pin: ScienceDigitalPin): number { return scienceInternal.digital(pin) }
}
